name: ARGUN CTI — Data Pipeline

on:
  schedule:
    - cron: '15 */2 * * *'
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'collectors/**'
      - 'enrichment/**'
      - 'output/**'
      - 'main.py'

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ARGUN CTI Pipeline
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py

      - name: Verify outputs
        run: |
          echo "=== Output Files ==="
          ls -la data/
          echo ""
          echo "=== CVE Feed Stats ==="
          python -c "
          import json
          with open('data/stats.json') as f:
              stats = json.load(f)
          s = stats['summary']
          print(f\"Total CVEs: {s['total_cves']}\")
          print(f\"Critical: {s['critical_count']}\")
          print(f\"KEV: {s['kev_count']}\")
          print(f\"PoC: {s['poc_count']}\")
          print(f\"IPs: {s['total_ips']}\")
          "

      - name: Commit and push data
        run: |
          git config --local user.email "cti-bot@argunsec.com"
          git config --local user.name "ARGUN CTI Bot"
          git add data/
          git diff --staged --quiet || git commit -m "🔄 CTI data update — $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
